### PR TITLE
Test Suite: install_default on rocky-8.5-[minimal|boot|dvd]-iso-x86_64

### LINKED ISSUE #16: Test suite failure for install_default@uefi on rocky-8.4-dvd-iso-x86_64
## Describe Issue
Test Suite | install_default@uefi 
-|-
Result  | **failed** ( 04:46 minutes )
Scheduled product |`rocky-8.4-dvd-iso-x86_64`
Test module | `/var/lib/openqa/share/tests/rocky/tests/_software_selection.pm `

## Analysis 
```
Test died: command 'egrep '(selected env|Selecting the.*environment)' /tmp/anaconda.log /tmp/packaging.log | tail -1 | grep custom-environment' failed at /var/lib/openqa/share/tests/rocky/tests/_software_selection.pm line 28.
```
This string indeed does not appear in the anaconda log. The comments around this line reference components that don't appear anywhere in this logfile:
```
# pre-F35 line looks like:
# 07:51:39,382 INF modules.payloads.payload.dnf.utils: selected environment: custom-environment          
# F35+ line looks like:
# 07:40:26,614 DBG ui.lib.software: Selecting the 'custom-environment' environment.
```

## Planned Action
* The tests are looking for a package group that exists in Fedora but not Rocky.
* Update the test to find a line in the logs referencing the correct package group.

### PR DESCRIPTION
**Pull request by akatch**
# Description

Updates standard test suites to complete installations of each default PACKAGE_SET for each ISO, based on data provided [here](https://github.com/tcooper/os-autoinst-distri-rocky/blob/issue_18/issue_18/RESULTS.md). These changes include updates to needles and `templates.fif.json` needed to make the tests pass.

Additionally, updates `templates.fif.json` to test relevant PACKAGE_SETs for each ISO, using the following conventions:
- Test suites will not be duplicated between the boot and dvd ISOs
- All default package sets will be tested against dvd-iso
- Boot ISO will be considered valid if `minimal` package set installs
  cleanly

This PR fixes #16 when merged.

# How Has This Been Tested?
```
# Reload your FIF templates as there were changes in this PR
./fifloader.py --clean --load templates.fif.json

# Verify default packagesets
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-minimal.iso ARCH=x86_64 DISTRI=rocky FLAVOR=minimal-iso VERSION=8.5 BUILD=i16_8.5_minimal-iso_20220209.221910.0 IDENTIFICATION=false TEST=install_minimal
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.5 BUILD=i16_8.5_dvd-iso_20220209.221906.0 IDENTIFICATION=false TEST=install_default
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.5 BUILD=i16_8.5_boot-iso_20220209.221902.0 IDENTIFICATION=false TEST=install_default

# Verify package selection menu looks correct for each valid PACKAGE_SET
# dvd-iso
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.5 BUILD=i16_dvd-iso_workstation_20220306.021009.0 TEST=install_package_set_workstation
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.5 BUILD=i16_dvd-iso_virtualization-host_20220306.021010.0 TEST=install_package_set_virtualization-host
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.5 BUILD=i16_dvd-iso_server_20220306.021011.0 TEST=install_package_set_server
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.5 BUILD=i16_dvd-iso_graphical-server_20220306.021012.0 TEST=install_package_set_graphical-server
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.5 BUILD=i16_dvd-iso_minimal_20220306.021013.0 TEST=install_package_set_minimal

# minimal-iso
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-minimal.iso ARCH=x86_64 DISTRI=rocky FLAVOR=minimal-iso VERSION=8.5 BUILD=i16_minimal-iso_server_20220306.021028.0 TEST=install_package_set_server
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-minimal.iso ARCH=x86_64 DISTRI=rocky FLAVOR=minimal-iso VERSION=8.5 BUILD=i16_minimal-iso_minimal_20220306.021028.0 TEST=install_package_set_minimal

# boot-iso
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.5 BUILD=i16_boot-iso_minimal_20220306.021045.0 TEST=install_package_set_minimal
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

## New warnings in this PR
This PR does generate softfailures of the login AVC as we have seen previously in the following suites:
- dvd-iso with PACKAGE_SET=virtualization-host
- dvd-iso with PACKAGE_SET=server

### CODE REVIEW

**Comment by tcooper** [comment]
Test of PR in progress... default package_sets all pass, on package selection menu verification now.

**Review by tcooper — COMMENTED** [review]
Suggested tests all ran successfully aside from standard soft fails for avc and one hard failure  in _console_wait_login / uefi_postinstall which we need to discuss.

There is potential issue with one needle where hostname on login screen is unexpected and is similar to issue seen in screen of my tests.

To discuss in next meeting to get confirmation.

**Comment by tcooper** [comment]
@lumarel The thing to look out for is the hostname in the openQA guest changing from localhost to whatever the hostname of your openQA dev system is. For @akatch the hostname is in one of the capture needles in this PR. On my test system it is `openqa-dev`...

_console_login

This happened in tests (2) that were complete passes and also in tests that had soft or full failures in the `_console_wait_login` or `_console_avc_crash`.

**Comment by tcooper** [comment]
For one of the tests where a crash log was generated (`PACKAGE_SET=virtualization_host`) the guests `/var/log/messages` clearly shows the hostname getting set when the `virbr0-nic` interface is activated by NetworkManager...

```
...
Mar  9 05:16:59 localhost NetworkManager[831]: <info>  [1646821019.7827] device (virbr0): Activation: successful, device activated.
Mar  9 05:16:59 localhost NetworkManager[831]: <info>  [1646821019.8072] device (virbr0-nic): state change: ip-check -> secondaries (reason 'none', sys-iface-state: 'external')
Mar  9 05:16:59 localhost NetworkManager[831]: <info>  [1646821019.8082] device (virbr0-nic): state change: secondaries -> activated (reason 'none', sys-iface-state: 'external')
Mar  9 05:16:59 localhost NetworkManager[831]: <info>  [1646821019.8143] device (virbr0-nic): Activation: successful, device activated.
Mar  9 05:16:59 localhost NetworkManager[831]: <info>  [1646821019.9406] policy: set-hostname: set hostname to 'openqa-dev' (from address lookup)
Mar  9 05:16:59 localhost systemd-hostnamed[863]: Changed host name to 'openqa-dev'
...
```

I'm not sure why the same happened in another test where `PACKAGE_SET=graphical_server`.

**Comment by lumarel** [comment]
I have ran all the tests mention up there now and the behavior Trevor is talking about is happening for me for the following tests (they have the hostname of the underlying worker server, so I'm seeing all 3 names of my different nodes):
- 00003940-rocky-8.5-dvd-iso-x86_64-Buildi16_dvd-iso_workstation_20220306.021009.0-install_package_set_workstation@uefi
- 00003937-rocky-8.5-dvd-iso-x86_64-Buildi16_8.5_dvd-iso_20220209.221906.0-install_default@uefi
- 00003942-rocky-8.5-dvd-iso-x86_64-Buildi16_dvd-iso_virtualization-host_20220306.021010.0-install_package_set_virtualization-host@64bit
- 00003943-rocky-8.5-dvd-iso-x86_64-Buildi16_dvd-iso_virtualization-host_20220306.021010.0-install_package_set_virtualization-host@uefi
- 00003947-rocky-8.5-dvd-iso-x86_64-Buildi16_dvd-iso_graphical-server_20220306.021012.0-install_package_set_graphical-server@uefi

**Review by lumarel — APPROVED** [review]
So, for me these changes look good 👌🏻
If the hostname make any problems in the future, we may want to fix that in the future, but didn't see anything up to now.
Thank you al!

**Comment by akatch** [comment]
I pulled the needle with my openQA host's hostname back out and am working on filing an issue for the hostname oddness now. Let me know if any other changes are needed. Thanks everybody for the reviews!

**Pull request merged**
