### PR TITLE
Modularity tests fix for  9.1  8.8  &  8.7

### LINKED ISSUE #147: [BUG] consistent failure in modularity_tests of FLAVOR=dvd-iso
## Describe the bug
The `modularity_tests` test of the `FLAVOR=dvd-iso` test suite fails consistently in Rocky 9 in production openQA system. Ref: [`modularity_tests`](https://openqa.rockylinux.org/tests/3413#next_previous).

The test `modularity_tests` in the `FLAVOR=dvd-iso` suite is a dependency of `install_default` which, for `dvd-iso` uses the `PACKAGE_SET=graphical_server`. There is no `PACKAGE_SET` defined in the Settings of the `modularity_tests` causing the implementation in [`modularity_module_list.pm#35`](https://github.com/rocky-linux/os-autoinst-distri-rocky/blob/develop/tests/modularity_module_list.pm#L35) to use the default `PACKAGE_SET=minimal`.

Further, the code in `modularity_module_list.pm` doesn't contain conditional blocks for Rocky Linux 8 and Rocky Linux 9. The enabled modules values for these two versions of Rocky Linux are not the same and need to be counted separately. The values in `modularity_module_list.pm` are valid for Rocky Linux 8 _**only**_.

## Expected behavior
The `modularity_tests` test of the `FLAVOR=dvd-iso` test suite passes consistently in Rocky Linux 9.

## Possible Solution
- The `modularity_tests` test must either detect which `PACKAGE_SET` was used to install the system it is testing or the proper `PACKAGE_SET` must be provided in `templates.fif.json`.
- The `FLAVOR=package_set` runs for Rocky Linux 9 can be used to obtain the default enabled modules for all `PACKAGE_SET` used with the DVD ISO.

## Screenshots

[**`modularity_tests@64bit `**](https://openqa.rockylinux.org/tests/3413#step/modularity_module_list/7)

modularity_tests_failure

## openQA.rockylinux.org:
 - os-autoinst-distri-rocky: commit: [366217e](https://github.com/rocky-linux/os-autoinst-distri-rocky/commit/366217ee8aac1d924017b807fbd03a7c7249e3ae)

### PR DESCRIPTION
**Pull request by AlanMarshall**
This PR fixes the consistent failure in the modularity_tests of the  FLAVOR=dvd-iso test suite  thereby resolving Issue #147
This branch is merged with PR#152 allowing in addition to 9.1 & 8.7  a successful test using version 8.8-lookahead:
Tested by:
```
openqa-cli api -X POST isos ISO=Rocky-9.1-20221214.1-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=9.1 BUILD=-"$(date +%Y%m%d.%H%M%S).0"-9.1-20221214.1-dvd-iso TEST=modularity_tests
openqa-cli api -X POST isos ISO=Rocky-8.7-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.7 BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.7-20221110-dvd-iso TEST=modularity_tests
openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.8 BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.8-dvd-iso TEST=modularity_tests
```
If merged first, this PR will supercede PR#152
fixes #147

### CODE REVIEW

**Review by tcooper — CHANGES_REQUESTED** [review]
The file `needles/rocky_do_install_and_reboot-prerelease_note-20230220.json` is missing the `ENV-DISTRI-rocky` tag.

Otherwise this appears OK.

PR was run through openQA with...

### Rocky 8.7

```
$ openqa-clone-custom-git-refspec --dry-run --verbose  https://github.com/rocky-linux/os-autoinst-distri-rocky/pull/156 https://openqa.rockylinux.org/tests/8299
```

NOTE: The `openqa-clone-job` command provided by above was modified to remove the `--skip-chained-deps` option allowing the parent test `default_upload` to produce new HDD for the `modularity_tests`. 

```
$ /usr/bin/openqa-clone-job --parental-inheritance --within-instance https://openqa.rockylinux.org 8299 _GROUP=0 TEST+=@AlanMarshall/os-autoinst-distri-rocky#modularity BUILD=AlanMarshall/os-autoinst-distri-rocky#156 CASEDIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#modularity PRODUCTDIR=os-autoinst-distri-rocky NEEDLES_DIR=rocky/needles
Cloning parents of rocky-8.7-dvd-iso-x86_64-Build20230302-Rocky-8.7-x86_64.0-modularity_tests@64bit
Cloning children of rocky-8.7-dvd-iso-x86_64-Build20230302-Rocky-8.7-x86_64.0-install_default_upload@64bit
Created job #8398: rocky-8.7-dvd-iso-x86_64-Build20230302-Rocky-8.7-x86_64.0-modularity_tests@64bit -> https://openqa.rockylinux.org/t8398
Created job #8397: rocky-8.7-dvd-iso-x86_64-Build20230302-Rocky-8.7-x86_64.0-install_default_upload@64bit -> https://openqa.rockylinux.org/t8397
```

openQA: https://openqa.rockylinux.org/tests/8398

### Rocky 9.1

```
$ openqa-clone-custom-git-refspec --dry-run --verbose  https://github.com/rocky-linux/os-autoinst-distri-rocky/pull/156 https://openqa.rockylinux.org/tests/8166
```

NOTE: The `openqa-clone-job` command provided by above was modified to remove the `--skip-chained-deps` option allowing the parent test `default_upload` to produce new HDD for the `modularity_tests`. 

```
$ /usr/bin/openqa-clone-job --parental-inheritance --within-instance https://openqa.rockylinux.org 8166 _GROUP=0 TEST+=@AlanMarshall/os-autoinst-distri-rocky#modularity BUILD=AlanMarshall/os-autoinst-distri-rocky#156 CASEDIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#modularity PRODUCTDIR=os-autoinst-distri-rocky NEEDLES_DIR=rocky/needles
Cloning parents of rocky-9.1-dvd-iso-x86_64-Build20230302-Rocky-9.1-x86_64.0-modularity_tests@64bit
Cloning children of rocky-9.1-dvd-iso-x86_64-Build20230302-Rocky-9.1-x86_64.0-install_default_upload@64bit
Created job #8399: rocky-9.1-dvd-iso-x86_64-Build20230302-Rocky-9.1-x86_64.0-install_default_upload@64bit -> https://openqa.rockylinux.org/t8399
Created job #8400: rocky-9.1-dvd-iso-x86_64-Build20230302-Rocky-9.1-x86_64.0-modularity_tests@64bit -> https://openqa.rockylinux.org/t8400
```

openQA: https://openqa.rockylinux.org/tests/8400

**Comment by AlanMarshall** [comment]
ENV-DISTRI-rocky  tag now added to  rocky_do_install_and_reboot-prerelease_note-20230220.json
This should resolve the request for changes.

**Review by tcooper — APPROVED** [review]

**Comment by AlanMarshall** [comment]
@tcooper I moved the new needles to more appropriate directories as a tidy up. No other changes.

**Review by tcooper — APPROVED** [review]

**Review by akatch — APPROVED** [review]
All tests pass, approved!

**Pull request merged**
