### PR TITLE
FIX: release_identification for Rocky Linux 9

### LINKED ISSUE #115: [BUG] release_identification fails for Rocky 9
**Describe the bug**
The `release_identification` test suite is hard-coded to only handle Rocky Linux 8 (Green Obsidian)

**To Reproduce**
``` 
$ openqa-cli api -X POST isos ISO=Rocky-9.0-RC1.1-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso PACKAGE_SET=minimal VERSION=9.0 BUILD=-minimal-$(date +%Y%m%d.%H%M%S).0 TEST=release_identification
```

**Expected behavior**
`release_identification` should properly detect all supported versions of Rocky Linux.

### PR DESCRIPTION
**Pull request by tcooper**
# Description

Resolves failures of `rocky_release` and `os_release` in `release_identification` test suite.

This PR is related to #114 and includes commits that @lumarel must have landed into his branch after the PR was created which would explain why his commits from June 27 are also included? Those commits are unrelated to this PR and I'm not sure the effect. I'll make this a DRAFT to be sure...

Resolves #115

# How Has This Been Tested?

```
$ openqa-cli api -X POST isos ISO=Rocky-9.0-RC1.1-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso PACKAGE_SET=minimal VERSION=9.0 BUILD=-minimal-$(date +%Y%m%d.%H%M%S).0 TEST=release_identification
```
I was unfortunately not able to fix all tests, but the new needles should fix a whole lot of tests (incl. help fully)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by akatch — APPROVED** [review]
I got a non-critical failure on `install_upload_default@_collect_data` but everything else looks good. Can take another pass if there are updates available.

**Review by lumarel — APPROVED** [review]
I ran that as cherry-picks on top of #117 and everything looks fine!
Thank you Trevor for fixing this! 🙂

**Comment by tcooper** [comment]
@akatch The non-critical failure for `_collect_data` is because that test attempts to install `tar` using `dnf` and repos inside the SUT are pointing at `pub` which doesn't exist (yet).

My next item to tackle is fixing some of the `lib/utils.pm` stuff so that we can point at staging (or even Peridot yumrepofs) repos for testing using test variables (like `LOCATION`). It's pretty easy to work on that with a completed `install_default_upload` in place (which I have).

That should fix this (and other) failures related to repository access like `base_update_cli`, `base_package_install_remove` and `modularity_tests`.

**Comment by lumarel** [comment]
We are moving forward, thank you Trevor once again!

**Pull request merged**
