### PR TITLE
Fix select root needle

### LINKED ISSUE #32: Test suite failure for install_software_raid on rocky-8.4-universal-x86_64
## Describe Issue

Test Suite | install_software_raid@64bit
-- | --
Result | failed ( 05:04 minutes )
Scheduled product | `rocky-8.4-universal-x86_64` after fixing PR for #21
Test module | `/var/lib/openqa/share/tests/rocky/tests/disk_custom_software_raid.pm`
Analysis | Test died: no candidate needle with tag(s) `anaconda_part_select_root` matched. at `/var/lib/openqa/share/tests/rocky/tests/disk_custom_software_raid.pm` line 14.

## Planned Action
- Update needle to match Rocky Linux Anaconda interface

### PR DESCRIPTION
**Pull request by lumarel**
## Description

Updates the `select_root_already_selected` needles to fix the broken `disk_custom_software_raid.pm`

## How Has This Been Tested?

- [x] Rerun of the whole test with the fixed needles `rocky-select_root_already_selected`

## How to test this

`openqa-cli api -X POST isos ISO=Rocky-8.4-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.4`

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

This PR fixes #32 and will automatically close when this is resolved.

### CODE REVIEW

**Comment by akatch** [comment]
I'm having trouble getting this one to work. Against this branch, the `install_software_raid@64bit` suite fails consistently at the `disk_custom_software_raid` module with this error: 

```
# Test died: no candidate needle with tag(s) 'anaconda_install_destination_select_disk_1' matched
```
Additionally, none of the other needles in this module appear to match up with the ones listed in this PR.

**Comment by lumarel** [comment]
@akatch Could you send me a screenshot of the mismatching needle with the matching? I will look into where it is not behaving 👌🏻

**Comment by akatch** [comment]
Gladly! It'll probably be later today though.

**Comment by StackKorora** [comment]
Confirmed it works with the previous MR.

**Pull request merged**
