### PR TITLE
Needle updates for 8.8 release

### PR DESCRIPTION
**Pull request by akatch**
# Description

This PR provides needle updates for the 8.8 release.

# How Has This Been Tested?

```
# openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.8 BUILD=-20230517.0-9.2_release-8.8
# openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.8 BUILD=-20230517.0-9.2_release-8.8
# openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=package-set VERSION=8.8 BUILD=-20230517.0-9.2_release-8.8
# openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-minimal.iso ARCH=x86_64 DISTRI=rocky FLAVOR=minimal-iso VERSION=8.8 BUILD=-20230517.0-9.2_release-8.8
# openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.8 BUILD=-20230517.0-9.2_release-8.8
```
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by AlanMarshall — DISMISSED** [review]
Tested ok.

**Comment by tcooper** [comment]
This looks like it only _**requires**_ testing with `server_cockpit_updates` as it's needles only. Concur?

**Review by AlanMarshall — APPROVED** [review]
[test 30576](https://openqa.rockylinux.org/tests/30576) has passed on prod and that's good enough for me.

**Review by lumarel — APPROVED** [review]
Also took another look, and yep good!

**Pull request merged**
