### PR TITLE
Fixes `_boot_to_anaconda` doesn't handle closest mirror gracefully in 8.5

### LINKED ISSUE #65: [BUG] `_boot_to_anaconda` doesn't handle closest mirror gracefully in 8.5
**Describe the bug**
Rocky 8.5 added a `closest mirror` capability to the anaconda installer. Since Rocky installer starts without network connected the `closest mirror` automatic resolution fails and changes the icon for the Software Selection even when a local media (ie. ISO) is being used. This can prevent detection of the `anaconda_main_hub` and block the installation.

**Steps to reproduce**
```
% openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-boot.iso \
  ARCH=x86_64 DISTRI=rocky FLAVOR=minimal-iso \
  VERSION=8.5 BUILD="-minimal-iso-$(date +%Y%m%d.%H%M%S).0"
```

**Expected behavior**
`_boot_to_anaconda` should detect this condition and allow the installation to proceed where the network interface will be activated in a later step and the `closest mirror` can be detected.

**Screenshots**

closest-mirror

**Desktop (please complete the following information):**
 - OS: Fedora 34 Server
 - Browser: Chrome 95.0.4638.69

### PR DESCRIPTION
**Pull request by tcooper**
## Description

This PR fixes #65 by providing a new needle, code and medium type modifications to connect the network interface automatically at boot.

## How Has This Been Tested?

```sh
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.5 BUILD=8.5_boot-iso_20211120.223231.0 PACKAGE_SET=minimal IDENTIFICATION=false
openqa-cli api -X POST isos ISO=Rocky-8.5-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.5 BUILD=8.5_boot-iso_20211120.223231.0 PACKAGE_SET=minimal IDENTIFICATION=false QEMUCPU=host GRUB="ip=dhcp mitigations=off"
```

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by akatch** [comment]
Before running these tests, make sure to reload your fifloader templates:

`./fifloader.py --clean --load templates.fif.json`

The specified test suites all connect to the network successfully. However, I am seeing a failure in `install_default@uefi` at the `uefi_postinstall` step. The failure message is `# Test died: no candidate needle with tag(s) 'root_console' matched`:

[](https://i.ibb.co/SPtqhX5/uefi-postinstall-failure.png)

Test report:

### Build8.5_boot-iso_20211121.121813.0
| Test | Result | Failure Reason | Effort to Fix | Notes |
| ---- | ------ | -------------- | ------------ | ----- |
| install_default@64bit | passed | | | |
| install_default@uefi | failed | `# Test died: no candidate needle with tag(s) 'root_console' matched` | | |


### Build8.5_boot-iso_20211121.121818.0
| Test | Result | Failure Reason | Effort to Fix | Notes |
| ---- | ------ | -------------- | ------------ | ----- |
| install_default@64bit | passed | | | |
| install_default@uefi | passed | | | |

**Review by akatch — COMMENTED** [review]
Will change this review to an approval on confirmation that the failure I'm seeing is unrelated to the fix for this test.

**Comment by tcooper** [comment]
> Will change this review to an approval on confirmation that the failure I'm seeing is unrelated to the fix for this test.

Interesting. Did you run the same POSTs I provided after running `./fifloader.py`? It was on oversight for me to include the `QEMUCPU=host` parameter POST as it should not be required. I'll rerun after rolling back my vm.

This is the case where also summarizing the test parameters used via `build_report.sh` might prove useful and / or it might be a good idea to always use the `archive` functionality when the job(s) were used to support a PR submission.

**Comment by akatch** [comment]
I did run the exact same POSTs as outlined in the description for this PR. However, I just reran that suite again, twice, and both times it passed. Race condition?

**Review by akatch — APPROVED** [review]

**Pull request merged**
