### PR TITLE
Fix/8.7 release batch 1

### PR DESCRIPTION
**Pull request by lumarel**
# Description

This fixes the following problems:

- prerelease screen needle
- cockpit tests

# How Has This Been Tested?

```bash
openqa-cli api -X POST isos ISO=Rocky-8.7-BETA-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.7 BUILD=-8.7-boot-iso-$(git branch --show-current)-$(date +%Y%m%d.%H%M%S).0
openqa-cli api -X POST isos ISO=Rocky-8.7-BETA-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso PACKAGE_SET=minimal VERSION=8.7 BUILD=-8.7-minimal-$(git branch --show-current)-$(date +%Y%m%d.%H%M%S).0
openqa-cli api -X POST isos ISO=Rocky-8.7-BETA-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso PACKAGE_SET=server VERSION=8.7 BUILD=-8.7-server-$(git branch --show-current)-$(date +%Y%m%d.%H%M%S).0
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by NeilHanlon** [comment]
i like the name of this image

`needles/anaconda/universal/rocky-accept_fate-20221006.png`

**Review by akatch — APPROVED** [review]

**Comment by tcooper** [comment]
If I read this correctly it appears to be a change that will prevent running cockpit for any release with FF <100. Is that correct?

**Comment by lumarel** [comment]
@tcooper As I mentioned in MM, should we keep the stuff for 8.6 as this will be merged when 8.7 gets published?
I sure can put in some logic to keep it, but it might not be needed anymore though.

**Comment by StackKorora** [comment]
> @tcooper As I mentioned in MM, should we keep the stuff for 8.6 as this will be merged when 8.7 gets published? I sure can put in some logic to keep it, but it might not be needed anymore though.

Once 8.7 releases, I don't think we should care about 8.6 so much. And if something comes up, we can always jump back in the Git commit to re-run tests.

**Comment by lumarel** [comment]
On another note, I think this change should actually also work for 8.6, I did not test this up to now but yeah the search box is also already there in 8.6!
So yeah not a blocker actually?

**Review by StackKorora — APPROVED** [review]
Lots of conversation in the Testing meeting about this, then follow up conversation in Mattermost.
Thanks for the contribution!

**Pull request merged**
