### PR TITLE
[9.0 Release Issues] Update package_set needles for 9.0 styling

### PR DESCRIPTION
**Pull request by akatch**
# Description

This PR updates needles for all of the package groups listed in the Package Selection spoke. These updates reflect the new GUI styling in 9.0. 

Related to #103 .

# How Has This Been Tested?
This PR includes updates to `templates.fif.json` so please be sure to run `fifloader.py`:
```
./fifloader.py --clean --load templates.fif.json
 openqa-cli api -X POST isos ISO=Rocky-9.0-RC1-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=9.0 BUILD=-boot-iso-$(date +%Y%m%d.%H%M%S).0 GRUB="inst.repo=https://dl.rockylinux.org/stg/rocky/9/BaseOS/x86_64/os/ inst.addrepo=AppStream,https://dl.rockylinux.org/stg/rocky/9/AppStream/x86_64/os/ ip=dhcp" TEST=install_package_set_server
 openqa-cli api -X POST isos ISO=Rocky-9.0-RC1-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=9.0 BUILD=-boot-iso-$(date +%Y%m%d.%H%M%S).0 GRUB="inst.repo=https://dl.rockylinux.org/stg/rocky/9/BaseOS/x86_64/os/ inst.addrepo=AppStream,https://dl.rockylinux.org/stg/rocky/9/AppStream/x86_64/os/ ip=dhcp" TEST=install_package_set_graphical-server
 openqa-cli api -X POST isos ISO=Rocky-9.0-RC1-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=9.0 BUILD=-boot-iso-$(date +%Y%m%d.%H%M%S).0 GRUB="inst.repo=https://dl.rockylinux.org/stg/rocky/9/BaseOS/x86_64/os/ inst.addrepo=AppStream,https://dl.rockylinux.org/stg/rocky/9/AppStream/x86_64/os/ ip=dhcp" TEST=install_package_set_workstation
 openqa-cli api -X POST isos ISO=Rocky-9.0-RC1-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=9.0 BUILD=-boot-iso-$(date +%Y%m%d.%H%M%S).0 GRUB="inst.repo=https://dl.rockylinux.org/stg/rocky/9/BaseOS/x86_64/os/ inst.addrepo=AppStream,https://dl.rockylinux.org/stg/rocky/9/AppStream/x86_64/os/ ip=dhcp" TEST=install_package_set_virtualization-host
 openqa-cli api -X POST isos ISO=Rocky-9.0-RC1-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=9.0 BUILD=-boot-iso-$(date +%Y%m%d.%H%M%S).0 GRUB="inst.repo=https://dl.rockylinux.org/stg/rocky/9/BaseOS/x86_64/os/ inst.addrepo=AppStream,https://dl.rockylinux.org/stg/rocky/9/AppStream/x86_64/os/ ip=dhcp" TEST=install_package_set_minimal
```

These needles should pass the `_software_selection` module at a minimum. It is expected that `workstation` and `graphical-server` will fail at the login screen until #109 is merged.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by lumarel — CHANGES_REQUESTED** [review]
Looks like you have to rebase, at least it wants to revert the changes from #108

**Comment by akatch** [comment]
> Looks like you have to rebase, at least it wants to revert the changes from #108

how about now

**Review by lumarel — APPROVED** [review]
Changes look good to me, only to not that the package sets, graphical server and workstation fail for me in `_graphical_wait_login` because the username is querty and it searches for test.
(but that might be out of scope here, so non-blocker)

**Comment by akatch** [comment]
I'm gonna go ahead and say the user is out of scope of this particular issue, we'll surely need to resolve it Eventually:tm: though.

**Pull request merged**
