### PR TITLE
Needles for `_graphical_wait_login` allowing English language Gnome environments to Getting Started

### LINKED ISSUE #48: Complete Test Suite for `_graphical_wait_login` allowing English language Gnome environments to Getting Started
## `_graphical_wait_login` fails for English language installs

Installs of `PACKAGE_SET={graphical-server,workstation}` in English language do not pass the initial Rocky EULA and/or Getting Started sequence for GNOME desktop environment.

## Planned Action

Provide needles and any code updates to allow English language GNOME installs to pass the EULA and Getting Started screens.

### PR DESCRIPTION
**Pull request by tcooper**
## Description

Add needles to enable completion of `_graphical_wait_login` screens for Rocky EULA and Getting Started in English language installs that have GNOME desktop.

Fixes #48  

## How Has This Been Tested?

- installed openQA dev host with Rocky Ansible playbook for openQA
- captured additional needles (as required)
- added additional test suites and job group to `templates.fif.json` to support brief `PACKAGE_SET` variation testing.
- ran with `POST` of DVD ISO for `FLAVOR=package-set`.
- `_graphical_wait_login` completed successfully.

### ISO POST

```bash
[rocky@openqa-dev rocky]$ openqa-cli api -X POST isos \
  ISO=Rocky-8.4-x86_64-dvd1.iso \
  ARCH=x86_64 \
  DISTRI=rocky \
  FLAVOR=package-set \
  VERSION=8.4 \
  BUILD=$(date +%Y%m%d.%H%M%S).0
```

_do_graphical_login

### Testsuite JSON for `server_cockpit_updates`

```bash
[rocky@openqa-dev needles]$ openqa-cli api jobs/295 | jq '.'
```

```json
{
  "job": {
    "assets": {
      "iso": [
        "Rocky-8.4-x86_64-dvd1.iso"
      ]
    },
    "assigned_worker_id": 1,
    "blocked_by_id": null,
    "children": {
      "Chained": [],
      "Directly chained": [],
      "Parallel": []
    },
    "clone_id": null,
    "group": "Rocky",
    "group_id": 1,
    "has_parents": 0,
    "id": 295,
    "name": "rocky-8.4-package-set-x86_64-Build20210918.203819.0-install_package_set_graphical-server@64bit",
    "parents": {
      "Chained": [],
      "Directly chained": [],
      "Parallel": []
    },
    "parents_ok": 1,
    "priority": 30,
    "result": "passed",
    "settings": {
      "ARCH": "x86_64",
      "ARCH_BASE_MACHINE": "64bit",
      "BACKEND": "qemu",
      "BUILD": "20210918.203819.0",
      "DESKTOP": "gnome",
      "DISTRI": "rocky",
      "ENCRYPT_PASSWORD": "weakpassword",
      "FLAVOR": "package-set",
      "ISO": "Rocky-8.4-x86_64-dvd1.iso",
      "MACHINE": "64bit",
      "NAME": "00000295-rocky-8.4-package-set-x86_64-Build20210918.203819.0-install_package_set_graphical-server@64bit",
      "PACKAGE_SET": "graphical-server",
      "PART_TABLE_TYPE": "mbr",
      "POSTINSTALL": "_console_login",
      "QEMUCPU": "Nehalem",
      "QEMUCPUS": "2",
      "QEMURAM": "2048",
      "QEMUVGA": "virtio",
      "QEMU_VIRTIO_RNG": "1",
      "ROOT_PASSWORD": "weakpassword",
      "TEST": "install_package_set_graphical-server",
      "TEST_SUITE_NAME": "install_package_set_graphical-server",
      "TEST_TARGET": "ISO",
      "USER_LOGIN": "qwerty",
      "VERSION": "8.4",
      "WORKER_CLASS": "qemu_x86_64"
    },
    "state": "done",
    "t_finished": "2021-09-19T05:09:06",
    "t_started": "2021-09-19T03:38:20",
    "test": "install_package_set_graphical-server"
  }
}
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by lumarel** [comment]
Hi @tcooper, I was unable to run this on top of develop.
As far as I can see #46 is needed, so this can completed successfully, will have to rerun it later, when I have the time 👌🏻
And it might be trivial to us, but if we add something to the fif files we also have to run the fif-loader again (nope I didn't fall over this, definitely not 👀)

**Comment by lumarel** [comment]
Okay did the second run! Looks good to me 👍🏻

**Comment by tcooper** [comment]
Yup... I assumed that those knowing how to test this would see the updated `templates.fif.json` and know that it would require a rerun of `fifloader.py`. That was a mistake.

Also, there does seem to be a dependency on #46 that I missed when pushing these up that I didn't notice in my test machine until I redeployed it and tried re-testing everything from a clean clone with PRs dropped sequentially onto develop.

@lumarel can you drop me the sequence you used to clone/pull the changes for testing so that I can compare with my sequence? I thought there were missing needles for #49 but they appear to be in #46 as you indicated.

**Comment by lumarel** [comment]
On the 2nd thought it really should be common knowledge, that the rerun is needed, it just was the only thing what was missing in the line ^^

@tcooper So my normal sequence is now to load the base `develop` branch and then `git fetch origin pull/49/head && git checkout FETCH_HEAD` on it to pull the PR changes (easily revertable by switching back to develop)
Here I needed to fork the repo, create a new branch based on `develop` and merge the two branches from your repo and then clone my forked branch. There might be a way how this can be done offline, but I was unable to find the correct sequence to create a offline branch where I could merge your branches.

**Comment by tcooper** [comment]
The last commit (I hope) to this PR restores the test suites for `PACKAGE_SET={minimal,server,virtualization-host}` to the `rocky-package-set` Job Group via an update to `templates.fif.json`. Yes... you must re-run `./fifloader.py ...` to make these available.

The following `POST` will trigger all 5 primary package set installs from the DVD ISO...

```bash
[rocky@openqa-dev rocky]$ openqa-cli api -X POST isos ISO=Rocky-8.4-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=package-set VERSION=8.4 BUILD=$(date +%Y%m%d.%H%M%S).0
{"count":5,"failed":[],"ids":[322,323,324,325,326],"scheduled_product_id":24}

[rocky@openqa-dev rocky]$ for i in {322..326}; do openqa-cli api jobs/${i} | jq '.[]["test"]'; done
"install_package_set_minimal"
"install_package_set_server"
"install_package_set_graphical-server"
"install_package_set_workstation"
"install_package_set_virtualization-host"
```

**Comment by lumarel** [comment]
Sorry for the delay, it took me some more time to test this more extensively now 🙂
@tcooper and @StackKorora I think this can also be merged 👌🏻

**Pull request merged**
