### PR TITLE
Provide tests for SIG/HPC slurm packages

### PR DESCRIPTION
**Pull request by akatch**
This MR provides a very, very basic test suite for the Slurm packages built by the HPC SIG. It checks the following:

- Necessary packages for a single-node Slurm instance install successfully from the SIG/HPC repository
- A job can be scheduled and executed to completion
- A job can be scheduled and then cancelled

# How Has This Been Tested?
```
./fifloader.py --clean --load templates.fif.json
openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.8 CURRREL=8 BUILD=-${date +%Y%m%d}.0-slurm-8.8 TEST=slurm22,slurm23
openqa-cli api -X POST isos ISO=Rocky-9.2-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=9.2 CURRREL=9 BUILD=-${date +%Y%m%d}.0-slurm-9.2 TEST=slurm22,slurm23
```

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tcooper** [comment]
Awesome @akatch for consideration... Do we want to adopt different JobGroup per SIG similar to how openSUSE do in their openQA? The tests themselves won't change but `templates.fif` will need adjustment.

**Comment by tcooper** [comment]
While I haven't run this in openQA (we cannot load `templates.fif.json` in prod system from PR) I have run your sequence in `rocky8u8` and `rocky9u2` VMs for both `slurm22` and `slurm23` versions.

I can confirm your sequence works as written and is sufficient for basic testing of SIG/HPC repository function and base slurm package installation.

We can discuss adding more of the produced packages to the scope of this test at a future meeting.

What we do need to discuss / decide is if/how we'll change `templates.fif.json` to create a Job Group for each SIG we support in openQA.

**Review by AlanMarshall — APPROVED** [review]
Tested x86_64 as specified using:
```
./fifloader.py --clean --load templates.fif.json
openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.8 CURRREL=8 BUILD=-"$(date +%Y%m%d.%H%M%S).0"-slurm-8.8 TEST=slurm22,slurm23
openqa-cli api -X POST isos ISO=Rocky-9.2-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=9.2 CURRREL=9 BUILD=-"$(date +%Y%m%d.%H%M%S).0"-slurm-9.2 TEST=slurm22,slurm23
```
Result: All Pass
Nice work Al

**Review by tcooper — APPROVED** [review]
Per discussion in team meeting we'll go ahead and merge this and put creation of JobGroup for SIG/HPC into a new PR.

**Pull request merged**
