### PR TITLE
r8.8 needles for anaconda_help

### PR DESCRIPTION
**Pull request by AlanMarshall**
Anaconda_help needles for r8.8
Tested:
```
openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.8 CURRREL=8 DNF_CONTENTDIR=stg DNF_RELEASEVER=8.8-Beta BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.8-beta-dvd-iso TEST=anaconda_help
```
Result:  Pass

### CODE REVIEW

**Comment by AlanMarshall** [comment]
I'm running out of ideas @tcooper 
I have tried all sorts of combinations based on the docs "Triggering tests based on an any remote Git refspec or open GitHub pull request" to get this tested on the prod system but I have not found how to pick up the new needles in the test.  So unless I get some new ideas, I have only the local tests as evidence of success.
The following was my starting point but it does not result in a working test:
```
openqa-clone-custom-git-refspec --verbose --dry-run    https://github.com/rocky-linux/os-autoinst-distri-rocky/pull/175    https://openqa.rockylinux.org/tests/26113
```

**Comment by tcooper** [comment]
@AlanMarshall Following the example [here](https://wiki.rockylinux.org/team/testing/dev_guides/openqa_clone_custom_git_refspec_examples/#advanced-openqa-clone-custom-git-refspec) I came up with the following `openqa-clone-job` command...
```bash
$ /usr/bin/openqa-clone-job \
    --skip-chained-deps \
    --parental-inheritance \
    --within-instance https://openqa.rockylinux.org 26113 \
    _GROUP=0 \
    TEST+=@AlanMarshall/os-autoinst-distri-rocky#8.8_needles \
    BUILD=AlanMarshall/os-autoinst-distri-rocky#175 \
    CASEDIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#8.8_needles \
    PRODUCTDIR=os-autoinst-distri-rocky \
    NEEDLES_DIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#8.8_needles/needles
Created job #26758: rocky-8.8-dvd-iso-x86_64-Build20230504-Rocky-8.8-Beta-x86_64.0-anaconda_help@64bit -> https://openqa.rockylinux.org/t26758
```

Have a look in a while and you should see the result.

**Comment by AlanMarshall** [comment]
Thanks @tcooper  that solves the problem for me.

The procedure I used now was:
06/05/23 (uk) or 05/06/23(us)   r8.8 needles test &  howto test needles on prod system; run:
```
openqa-clone-custom-git-refspec --verbose --dry-run    https://github.com/rocky-linux/os-autoinst-distri-rocky/pull/175    https://openqa.rockylinux.org/tests/26113
```
where ```175``` is the pull request number and 25113 is the previous test to clone
which produces:
```
/usr/bin/openqa-clone-job --skip-chained-deps --parental-inheritance --within-instance https://openqa.rockylinux.org 26113 _GROUP=0 TEST+=@AlanMarshall/os-autoinst-distri-rocky#8.8_needles BUILD=AlanMarshall/os-autoinst-distri-rocky#175 CASEDIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#8.8_needles PRODUCTDIR=os-autoinst-distri-rocky NEEDLES_DIR=rocky/needles
```
in ```NEEDLES_DIR=rocky/needles``` replace ```rocky``` with the contents of ```CASEDIR=```
giving:
```
/usr/bin/openqa-clone-job --skip-chained-deps --parental-inheritance --within-instance https://openqa.rockylinux.org 26113 _GROUP=0 TEST+=@AlanMarshall/os-autoinst-distri-rocky#8.8_needles BUILD=AlanMarshall/os-autoinst-distri-rocky#175 CASEDIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#8.8_needles PRODUCTDIR=os-autoinst-distri-rocky NEEDLES_DIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#8.8_needles/needles
```
which now picks up the new needles and runs  with result: pass

Thanks again Trevor, that was most helpful.

**Review by tcooper — APPROVED** [review]

**Review by lumarel — APPROVED** [review]
LGTM, thanks for all your great work Alan!

**Comment by AlanMarshall** [comment]
Thanks Lukas and Trevor. I'll merge this for now to get it going and put the needles to their appropriate directories later.

**Pull request merged**
