### PR TITLE
Anaconda text install

### PR DESCRIPTION
**Pull request by AlanMarshall**
Added new needle for text install.
Deleted redundant code.
Tested for 9.1, 8.7 & 8.8:
```
openqa-cli api -X POST isos ISO=Rocky-9.1-20221214.1-x86_64-dvd.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=9.1 BUILD=-"$(date +%Y%m%d.%H%M%S).0"-9.1-20221214.1-universal TEST=install_anaconda_text
openqa-cli api -X POST isos ISO=Rocky-8.7-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.7 BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.7-20221110-universal TEST=install_anaconda_text
openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.8 BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.8-lookahead-universal TEST=install_anaconda_text
```
Result: Pass
Fixes Issue #145

### CODE REVIEW

**Review by akatch — APPROVED** [review]
All indicated tests pass.

**Comment by tcooper** [comment]
While the test run for this PR [passes in the openQA production system for Rocky Linux 8.7](https://openqa.rockylinux.org/tests/13415) it [fails for Rocky Linux 9.1](https://openqa.rockylinux.org/tests/13416#) stalling at a menu choice between Start VNC and Use text mode.

This appears to be triggered in 9.1 because the network is up on boot while it is not up in Rocky Linux 8. I cannot explain why both @AlanMarshall and @akatch report this as passing.

A possible resolution would be to add check for Rocky Linux major version at line 107 in [`_boot_to_anaconda`](https://github.com/AlanMarshall/os-autoinst-distri-rocky/blob/6c788a69afe191bed11b584eb95624d5e1861b7e/tests/_boot_to_anaconda.pm#L107) effectively making the first block match for Rocky Linux 8 while the second block (current Fedora only) match for Rocky Linux 9+.

**Comment by AlanMarshall** [comment]
@tcooper  It appears from your test results that neither of your tests is picking up the new needle:
https://github.com/AlanMarshall/os-autoinst-distri-rocky/blob/anaconda-txt/needles/anaconda/main_hub/rocky-anaconda_main_hub_text-20230317.*
so they demonstrate the correct pre-fix result.
cc @akatch

**Comment by tcooper** [comment]
@AlanMarshall Not picking up the new needle is possible but when I had a closer look at the test the place where I think you added that needle isn't actually what we want. I'll submit another/alternate PR for that explains/demonstrates what we need here.

**Comment by AlanMarshall** [comment]
Superceded by #163

**Pull request closed without merging**
