### PR TITLE
Correct needle to properly detect network connected

### LINKED ISSUE #68: [BUG] Needle in PR #66 breaks minimal install when `GRUB="ip=dhcp"` is not set
**Describe the bug**
The needle added in #66 to resolve `_boot_to_anaconda` issue in text install is not specific enough and also matches when using `dvd-iso` with a server based install and no network connection is required. In that case the test passes until the final stage where network access is required for `_collect_data`. Without network enabled `_collect_data` is a hard failure.

**To Reproduce**
1. Clone repo and/or update latest `devel` branch to include #66 
2. POST the standard `minimal` case
3. Installation will succeed but `_collect_data` will fail with no network access to upload results to openQA.

**Expected behavior**
Network interface should ALWAYS be enabled and minimal test should complete regardless of whether a `GRUB=...` variable is configured to preset the network interface connection (or not).

**Desktop (please complete the following information):**
 - OS: Fedora 34 Server with openQA
 - Browser: Chrome 96.0.4664.5
 - Version: This repo at [33dd37f](https://github.com/rocky-linux/os-autoinst-distri-rocky/commit/33dd37fdea09e9b1e6ca297e79f4fdca46436b7d) 

**Additional context**
It appears only a fix to the needle to make it more specific is required and additional logic in `_anaconda_network_enable.pm` is not required.

### PR DESCRIPTION
**Pull request by tcooper**
### Description

This PR fixes #68 to allow needle match when network is connected before entering Network spoke and when network is not required for install for `minimal-iso` and `dvd-iso` flavors.

Before this change needle would also match if network was not connected but _not_ required (ie. `minimal-iso` or `dvd-iso`).

_NOTE: Perhaps the smallest fix yet... 32 pixels... but **hours** wasted._

### How Has This Been Tested?

```sh
$ openqa-cli api -X POST isos \
    ISO=Rocky-8.5-x86_64-minimal.iso \
    ARCH=x86_64 DISTRI=rocky \
    FLAVOR=minimal-iso \
    VERSION=8.5 \
    BUILD=$(date +%Y%m%d.%H%M%S).0 \
    GRUB="ip=dhcp"
    
$ openqa-cli api -X POST isos \
    ISO=Rocky-8.5-x86_64-minimal.iso \
    ARCH=x86_64 \
    DISTRI=rocky \
    FLAVOR=minimal-iso \
    VERSION=8.5 \
    BUILD=$(date +%Y%m%d.%H%M%S).0
    
$ openqa-cli api -X POST isos \
    ISO=Rocky-8.5-x86_64-dvd1.iso \
    ARCH=x86_64 \
    DISTRI=rocky \
    FLAVOR=dvd-iso \
    VERSION=8.5 \
    BUILD=$(date +%Y%m%d.%H%M%S).0 \
    GRUB="ip=dhcp" \
    TEST=install_lvm_ext4 \
    PACKAGE_SET=server
    
$ openqa-cli api -X POST isos \
    ISO=Rocky-8.5-x86_64-dvd1.iso \
    ARCH=x86_64 \
    DISTRI=rocky \
    FLAVOR=dvd-iso \
    VERSION=8.5 \
    BUILD=$(date +%Y%m%d.%H%M%S).0 \
    TEST=install_lvm_ext4 \
    PACKAGE_SET=server
```

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation where required
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by akatch** [comment]
PR looks good. On my first pass I encountered one failure which I believe is an environmental performance thing. I'm rerunning to be sure. Here's my initial test report:

# Build8.5_minimal-iso_20211205.001108.0

	$ openqa-cli api -X POST isos \
		ISO=Rocky-8.5-x86_64-minimal.iso \
		ARCH=x86_64 DISTRI=rocky \
		FLAVOR=minimal-iso \
		VERSION=8.5 \
		BUILD=8.5_minimal-iso_$(date +%Y%m%d.%H%M%S).0 \
		GRUB="ip=dhcp"


| Test | Result | Failure Reason | Effort to Fix | Notes |
| ---- | ------ | -------------- | ------------- | ----- |
| install_minimal@64bit | passed | | | |
| install_minimal_upload@64bit | passed | | | |
# Build8.5_minimal-iso_20211205.001216.0

	$ openqa-cli api -X POST isos \
		ISO=Rocky-8.5-x86_64-minimal.iso \
		ARCH=x86_64 \
		DISTRI=rocky \
		FLAVOR=minimal-iso \
		VERSION=8.5 \
		BUILD=8.5_minimal-iso_$(date +%Y%m%d.%H%M%S).0

| Test | Result | Failure Reason | Effort to Fix | Notes |
| ---- | ------ | -------------- | ------------- | ----- |
| install_minimal@64bit | passed | | | |
| install_minimal_upload@64bit | failed | Failed to match "anaconda_install_done" needle, because the installation took longer than expected. I'm rerunning this one, believe it's a non-blocking failure. | | |
# Build8.5_dvd-iso_20211205.001335.0

	$ openqa-cli api -X POST isos \
		ISO=Rocky-8.5-x86_64-dvd1.iso \
		ARCH=x86_64 \
		DISTRI=rocky \
		FLAVOR=dvd-iso \
		VERSION=8.5 \
		BUILD=8.5_dvd-iso_$(date +%Y%m%d.%H%M%S).0 \
		GRUB="ip=dhcp" \
		TEST=install_lvm_ext4 \
		PACKAGE_SET=server

| Test | Result | Failure Reason | Effort to Fix | Notes |
| ---- | ------ | -------------- | ------------- | ----- |
| install_lvm_ext4@64bit | softfailed | AVCs found: `audit(1638686232.075:74): avc:  denied  { getattr } for  pid=1082 comm="login" name="/" dev="tmpfs"` | | |
| install_lvm_ext4@uefi | softfailed | AVCs found: `audit(1638686256.063:74): avc:  denied  { getattr } for  pid=1089 comm="login" name="/" dev="tmpfs"`| | |
# Build8.5_dvd-iso_20211205.001342.0

	$ openqa-cli api -X POST isos \
		ISO=Rocky-8.5-x86_64-dvd1.iso \
		ARCH=x86_64 \
		DISTRI=rocky \
		FLAVOR=dvd-iso \
		VERSION=8.5 \
		BUILD=8.5_dvd-iso_$(date +%Y%m%d.%H%M%S).0 \
		TEST=install_lvm_ext4 \
		PACKAGE_SET=server

| Test | Result | Failure Reason | Effort to Fix | Notes |
| ---- | ------ | -------------- | ------------- | ----- |
| install_lvm_ext4@64bit | softfailed | AVCs found: `audit(1638687101.493:74): avc:  denied  { getattr } for  pid=1091 comm="login" name="/" dev="tmpfs"`| | |
| install_lvm_ext4@uefi | softfailed | AVCs found: `audit(1638687150.002:74): avc:  denied  { getattr } for  pid=1095 comm="login" name="/" dev="tmpfs"` | | |

**Review by akatch — APPROVED** [review]
The one failure I got in my first run passed on a rerun. I think I need to find and increase the timeout, since I keep running into this. Anyways, looks good to me.

**Comment by tcooper** [comment]
> The one failure I got in my first run passed on a rerun. I think I need to find and increase the timeout, since I keep running into this. Anyways, looks good to me.

I have a couple of standard changes that I make that generally takes care of these.

```diff
➜  os-autoinst-distri-rocky git:(install_destination) ✗ git --no-pager diff
diff --git a/tests/_do_install_and_reboot.pm b/tests/_do_install_and_reboot.pm
index af2d6225..03105f65 100644
--- a/tests/_do_install_and_reboot.pm
+++ b/tests/_do_install_and_reboot.pm
@@ -112,8 +112,8 @@ sub run {
     # we're on a debug kernel, debug kernel installs are really slow.
     my $timeout = 1800;
     my $version = lc(get_var('VERSION'));
-    if ($version eq "rawhide") {
-        $timeout = 2400;
+    if ($version eq "rawhide" || lc(get_var('DISTRI')) eq "rocky") {
+        $timeout = 4800;
     }
     # workstation especially has an unfortunate habit of kicking in
     # the screensaver during install...
diff --git a/tests/install_text.pm b/tests/install_text.pm
index 26f015d7..f86ba721 100644
--- a/tests/install_text.pm
+++ b/tests/install_text.pm
@@ -153,7 +153,7 @@ sub run {
     # we're on a debug kernel, debug kernel installs are really slow.
     my $timeout = 1800;
     if (lc(get_var('VERSION')) eq "rawhide" || lc(get_var('DISTRI')) eq "rocky") {
-        $timeout = 2400;
+        $timeout = 4800;
     }

     if (testapi::is_serial_terminal) {
```


I can add a PR with them to get them included as defaults if you want. I thought I was the only one running into them. Almost anywhere there are longer timeouts for `rawhide` we can add to the conditional and option for `DISTRI=rocky` and double the timeout.

**Comment by akatch** [comment]
Perfect, that would be awesome if you could toss up a PR for adding this
to defaults. I seem to run into it only sporadically, when I've got all
my workers working at a time... but it's kind of annoying nonetheless.

**Pull request merged**
