### PR TITLE
Update pre-release logic for BETA testing

### PR DESCRIPTION
**Pull request by tcooper**
This PR updates the logic in `check_prerelease()` to correctly match LABEL likely to be used and to also set `prerelease=1` for `Beta|BETA|LookAhead` ISOs.

Needles are added from installer screens of Rocky Linux 8.10-BETA for default and additional languages.

Related to these updates the use of `CURRREL` in `repos_mirrorlist()` is deprecated in favor of `VERSION` and the definition of `setup_workaround_repo()` and it's use was deprecated.

## openqa-clone-custom-git-refspec tests

install_default - https://openqa.rockylinux.org/tests/117798#step/_boot_to_anaconda/11
install_arabic_language - https://openqa.rockylinux.org/tests/117799#step/_boot_to_anaconda/11
install_asian_language - https://openqa.rockylinux.org/tests/117801#step/_boot_to_anaconda/11
install_european_language - https://openqa.rockylinux.org/tests/117802#step/_boot_to_anaconda/11

**NOTE: The `prerelease_note` needle match in these tests is the part that needs to be checked in the context of this PR. But, at least in the language tests, there are other issues that may block merge of this PR unless/until verified.**

### CODE REVIEW

**Review by AlanMarshall — CHANGES_REQUESTED** [review]
Tested:
```
openqa-cli api -X POST isos ISO=Rocky-8.10-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.10 LABEL=BETA DNF_CONTENTDIR=stg/rocky DNF_RELEASEVER=8-BETA BUILD=-"$(date +%Y%m%d.%H%M%S).0"-dvd-iso-8.10-BETA
openqa-cli api -X POST isos ISO=Rocky-8.10-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.10 LABEL=BETA DNF_CONTENTDIR=stg/rocky DNF_RELEASEVER=8-BETA BUILD=-"$(date +%Y%m%d.%H%M%S).0"-universal-8.10-BETA
openqa-cli api -X POST isos ISO=Rocky-8.10-20240326.t.0-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.10 LABEL=BETA DNF_CONTENTDIR=stg/rocky DNF_RELEASEVER=8-BETA GRUBADD=inst.repo=https://dl.rockylinux.org/stg/rocky/8-BETA/BaseOS/x86_64/os/ BUILD=-"$(date +%Y%m%d.%H%M%S).0"-boot-iso-8.10-BETA
```
Result: 
1) Language tests and install_default results were identical to those in the prod system tests above, and in the full runs, all prerelease checks were ok.
2) Checked that if LABEL=BETA or LABEL=Beta is not set as such then the prerelease needles are not used.
3) However, there is a new issue with the multi-vm tests:

 support server is failing to find it's HDD1
```
HDD_1 handling Cannot find HDD_1 asset hdd/disk_rocky_support_x86_64.qcow2!
from createhdds the file is:  Apr  4 19:15 disk_rocky8_support_x86_64.qcow2
```
and server_realmd_join_kickstart fails to find HDD2 as:
```
HDD_2 handling Cannot find HDD_2 asset hdd/disk_ks-.img!
from createhdds the file is:   disk_ks-8.img
```

**Comment by tcooper** [comment]
@AlanMarshall You **must** provide a value for `CURRREL` for the `HDD{1,2}` paths defined in `templates.fif.json` to be generated properly (eg. [support_server](https://github.com/rocky-linux/os-autoinst-distri-rocky/blob/develop/templates.fif.json#L1732)). The POST variable `CURRREL` is not completely deprecated. Only it's use in `repos_mirrorlist` where `VERSION` is more appropriate is changed.

**Comment by AlanMarshall** [comment]
@tcooper  Oops sorry Trevor, I didn't notice that. I'll run the tests again tomorrow to check properly.

**Review by AlanMarshall — APPROVED** [review]

**Review by AlanMarshall — APPROVED** [review]
Tested:
```
./fifloader.py -c -l templates.fif.json
openqa-cli api -X POST isos ISO=Rocky-8.10-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.10 CURRREL=8-BETA LABEL=BETA DNF_CONTENTDIR=stg/rocky DNF_RELEASEVER=8-BETA BUILD=-"$(date +%Y%m%d.%H%M%S).0"-dvd-iso-8.10-BETA
openqa-cli api -X POST isos ISO=Rocky-8.10-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.10 CURRREL=8-BETA LABEL=BETA DNF_CONTENTDIR=stg/rocky DNF_RELEASEVER=8-BETA BUILD=-"$(date +%Y%m%d.%H%M%S).0"-universal-8.10-BETA
openqa-cli api -X POST isos ISO=Rocky-8.10-20240326.t.0-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.10 CURRREL=8-BETA LABEL=BETA DNF_CONTENTDIR=stg/rocky DNF_RELEASEVER=8-BETA GRUBADD=inst.repo=https://dl.rockylinux.org/stg/rocky/8-BETA/BaseOS/x86_64/os/ BUILD=-"$(date +%Y%m%d.%H%M%S).0"-boot-iso-8.10-BETA

```
Result:
1) Language tests and install_default results were identical to those in the prod system tests above, and in the full runs, all prerelease checks were ok.
2) Checked that if LABEL=BETA or LABEL=Beta is not set as such then the prerelease needles are not used.
3) However, there is a still a slight issue with the multi-vm tests relating to createhdds which I don't think is important in the present context:

server_realmd_join_kickstart fails to find HDD2 as:
```
HDD_2 handling Cannot find HDD_2 asset hdd/disk_ks-8-BETA.img!
from createhdds the file is:   disk_ks-8.img
```

Overall, works a treat now that I have the command line correct.  *Should have read the diffs more carefully the first time. tut tut*

**Pull request merged**
