### PR TITLE
Enable staging repos when DNF_CONTENTDIR is specified

### PR DESCRIPTION
**Pull request by akatch**
This PR adds no new functionality but re-enables some logic to enable staging repositories when DNF_CONTENTDIR is supplied.

### CODE REVIEW

**Review by AlanMarshall — COMMENTED** [review]
I have tested this using:
```
openqa-cli api -X POST isos ISO=Rocky-8.8-20230330.t.2-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.8 CURRREL=8 DNF_CONTENTDIR=stg GRUBADD=inst.repo=https://download.rockylinux.org/stg/rocky/8.8-BETA/BaseOS/x86_64/os BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.8-beta-boot-iso
```
Result:  Both tests fail  in  _staging_repos_enable.pm line 11

Test incomplete:
Reason: backend died: No map for '' at /usr/lib/os-autoinst/consoles/VNC.pm line 660.

**Comment by AlanMarshall** [comment]
This is not looking good. I'm getting exact same incomplete tests with 8.7 stg.
Tested using:
```
openqa-cli api -X POST isos ISO=Rocky-8.7-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.7 CURRREL=8 DNF_CONTENTDIR=stg GRUBADD=inst.repo=https://dl.rockylinux.org/stg/rocky/8.7/BaseOS/x86_64/os BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.7-stg-boot-iso
```
Investigation is continuing...

**Comment by tcooper** [comment]
@AlanMarshall Don't spend more time debugging this error issue other than to simply solve a puzzle. I forgot how this contentdir change is implemented and this PR isn't required after all. @akatch please leave this PR open until we discuss as it serves as a good example of how to test this in the production instance.

**Comment by AlanMarshall** [comment]
Yes, thanks @tcooper  from tests I am well on the way to a very similar conclusion and was about to report as such.

**Comment by AlanMarshall** [comment]
@tcooper I confirm that your results are exactly what my tests showed. The failure in ```script_run sed -i...``` was due to having no map for key ```#0001``` which is probably ascii SOH. The failure occurs only after reboot when sed (or rsync) try to replace ```/etc/yum.repos.d/Rocky-*``` and does not occur when the same commands are run at the end of the install phase. However, ```/etc/yum.repos.d/Rocky-*``` can be read after reboot without any failure occurring.
@akatch I found that having a modified ```tests/_staging_repos_enable.pm``` was very useful in working out what was going on here and I therefore suggest retaining and extending PR #169 to provide an ongoing debug facility that only operates when the stg repos are being used via ```DNF_CONTENTDIR=stg```. After all we have this existing code that can be modified and used to advantage for development rather than just deleting it as redundant.
Does this seem reasonable to everyone?

**Comment by AlanMarshall** [comment]
As a suggestion, this is what I'm thinking of for now:
```
use base "installedtest";
use strict;
use testapi;
use utils;

sub run {
    my $self = shift;
    $self->root_console(tty => 4);
    script_run 'ls -alh /etc/yum.repos.d/';
    if (get_version_major() < 9) {
        script_run 'cat /etc/yum.repos.d/Rocky-BaseOS.repo';
    } else {
        script_run 'cat /etc/yum.repos.d/rocky-BaseOS.repo';
    }
    # Check dnf pointing at staging repos
    script_run 'cat /etc/dnf/vars/contentdir';
    script_run 'dnf clean all';
    # Check enabled repos
    script_run 'dnf repoinfo';
}

sub test_flags {
    return {fatal => 1};
}

```
The results appear as a row in the openqa run details page.
The ```dnf repoinfo``` result has identified the postinstall enabled repos as including:
```http://dl.rockylinux.org/stg/rocky/8/BaseOS/x86_64/os/```

and similar for ```AppStream``` and ```extras```  whereas the enabled repos should be:
```http://dl.rockylinux.org/stg/rocky/8.8-Beta/BaseOS/x86_64/os/```

I tried various combinations of VERSION=8.8-Beta and CURREL=8 with same result. Maybe there is another parameter that I haven't discovered yet...  If not then this is a bug that needs fixing.
One of the commands that I tried was:
```
openqa-cli api -X POST isos ISO=Rocky-8.8-20230330.t.2-x86_64-boot.iso ARCH=x86_64 DISTRI=rocky FLAVOR=boot-iso VERSION=8.8-Beta CURREL=8.8-Beta DNF_CONTENTDIR=stg GRUBADD=inst.repo=https://dl.rockylinux.org/stg/rocky/8.8-Beta/BaseOS/x86_64/os BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.8-beta-boot-iso
```
Result always: ```http://dl.rockylinux.org/stg/rocky/8/BaseOS/x86_64/os/```

I would also rename ```_staging_repos_enable.pm``` to something more appropriate.

**Pull request closed without merging**
