### PR TITLE
Update and Provide FreeIPA Tests

### PR DESCRIPTION
**Pull request by nazunalika**
Hello. This PR attempts to address the following for FreeIPA tests:

* Modify FreeIPA tests to try to match core's toolkit (func)
* Add variable assignment for repeated values/domains/realms
  * This will need some validation due to escapes being used on `@` in various places
* Prepare realm portions such as cockpit and password changes in webui
* Change fedoraproject.org domain to rockylinux.org domain

### CODE REVIEW

**Comment by tcooper** [comment]
@nazunalika This PR has been run in openQA and failed. You will find feedback/output here... https://openqa.rockylinux.org/tests/8743

**Comment by nazunalika** [comment]
Syntax errors should be resolved now.

**Comment by tcooper** [comment]
@nazunalika `Use of uninitialized value in bitwise and (&) at os-autoinst-distri-rocky/main.pm line 333.` See https://openqa.rockylinux.org/tests/8744

**Comment by tcooper** [comment]
@nazunalika Thanks for this fix though I don't think it is the core of the problem with this test. See the lines following that where there are multiple syntax errors reported in `tests/realmd_join_sssd.pm`.

**Comment by tcooper** [comment]
@nazunalika I've tried to resolve the various syntax errors in these tests but the backend is still complaining about the syntax you've provided. Linter/code checker doesn't have the same complaints so I'm really not sure what is up. Most recent failure is here (https://openqa.rockylinux.org/tests/10988). Can you have another look at the code it is complaining about?

If somebody else with a testing env for openQA can run this PR and come up with changes that will fix the failures that would be most helpful.

**Comment by nazunalika** [comment]
It is likely because we were missing the use feature directive to allow the use of "given". See if that resolves the issue.

**Comment by tcooper** [comment]
@nazunalika

- Syntax errors appear to be resolved and latest test run starts to do something that produces results that can be examined.
- In `server_freeipa_replication_master` the hostname is set to `ipa002.test.openqa.fedoraproject.org` in `_post_network_static` which won't trigger a failure unless other hosts expect a different domain.
- For some reason `server_freeipa_replication_master` isn't dropping to root console in `role_deploy_domain_controller` causing that test to fail triggerring parallel_failed.

See... https://openqa.rockylinux.org/tests/12341# for more details.

**Comment by nazunalika** [comment]
I modified the FIF template to try to get around the hostnames, but I don't know if that is the right thing to do here. (I am of the opinion we should be using our own domain where possible for consistency, but I don't know if it matters to the team). If the replica-to-be has a hostname that isn't in the same domain, becoming a replica can sometimes have problematic results and it isn't guaranteed to succeed.

**Comment by tcooper** [comment]
Those changes look good for hostnames and I agree these should all be changed to our own domain. There are a few more in some other tests which we'll also need to take care of in separate PRs.

I can post a test of these changes but for the {{templates.fif.json}} update I'll need to clone an existing job and supply those options on the command line as PR runs don't modify {{templates.fif.json}}... it's a chicken-and-egg problem.

Hopefully, the failure of `server_freeipa_replication_master` to drop to root console was a one-off. That problem didn't exist in the replica instance.

**Comment by tcooper** [comment]
OK... clone of job and supply `POST_STATIC` for the job didn't work. It applied the tap configuration to the parent `install_default_upload` job causing that test to fail and breaking the whole parallel run. I think this PR is going to need to be directly tested / fixed by somebody with a working multi-worker DEV setup or the mods to the `templates.fif.json` will need to be merged in as is in order to do more testing. Will discuss in today's meeting...

**Review by tcooper — APPROVED** [review]
Changes provided here are largely working and have been tested as possible in the openQA production system. Additionally, the sequences to setup the FreeIPA server and connect the client have been recreated in VMs to validate / troubleshoot and a small number of issues have been resolved.

These changes should be approved and merged and any remaining problems addressed directly.

**Review by AlanMarshall — APPROVED** [review]
I can't test this since I don't have multi-worker tests installed (yet).

However I have studied the changes and I am happy to accept that they should be approved and merged now so that any remaining problems can be addressed directly.

**Pull request merged**
