### PR TITLE
Fix Network Install selection Needle

### LINKED ISSUE #22: Test suite failure for install_mirrorlist_graphical on rocky-8.4-universal-x86_64
## Describe Issue

Test Suite | install_mirrorlist_graphical@64bit 
-- | --
Result | failed ( 04:35 minutes )
Scheduled product | `rocky-8.4-universal-x86_64`
Test module | `/var/lib/openqa/share/tests/rocky/tests/install_source_graphical.pm`
Analysis | Test died: no candidate needle with tag(s) `anaconda_install_source_on_the_network` matched. at `/var/lib/openqa/share/tests/rocky/tests/install_source_graphical.pm` line 17.

## Planned Action
- Update needle to match Rocky Linux Anaconda interface

### PR DESCRIPTION
**Pull request by lumarel**
## Description

Updates the `on_the_network` needle to fix the broken `install_source_graphical.pm`

## How Has This Been Tested?

- [x] Rerun of the whole test with the fixed needle `rocky-on_the_network`

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

This PR fixes #22 and will automatically close when this is resolved.

Little note:
It sometimes happens that the mirrorlist does not get accepted because the internet connection is not fully setup until this point, depends on the speed of the internet connection, we might want to check that if it makes more problems.

### CODE REVIEW

**Comment by tcooper** [comment]
@lumarel I'm not sure how you `POST`'ed this test. Can you add a comment with your `POST` command-line? Also, check to see if these changes also help a `POST` with the boot iso get running past the `anaconda_main` screen?

**Comment by lumarel** [comment]
@tcooper Oh yeah sure, this is from the universal suite:
`openqa-cli api -X POST isos ISO=Rocky-8.4-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.4`
This is unfortunately a really big testsuite, if somehow possible you might want to only run the `install_mirrorlist_graphical@64bit` test, it should be possible to run it individually somehow as it uses the ISO as starting point.

Sorry I really should have added that... we might have that in our template, to always post the api post..

**Comment by lumarel** [comment]
And about the `boot-iso` is that the network is not already connected during the bootup, which then marks the installation source with a warning, which breaks the needle there.
I didn't have the time to look into how this should be fixed the best, but it is definitely something for a new issue

**Comment by akatch** [comment]
Ran the provided test command and confirmed that the `rocky-on_the_network` needle matches in the `install_source_graphical` module. I did run into the mirrorlist failure, but this PR does seem to work as advertised.

**Comment by StackKorora** [comment]
Confirmed.

**Pull request merged**
