### PR TITLE
r8.8 needles for cockpit

### PR DESCRIPTION
**Pull request by AlanMarshall**
This completes the set of needles for r8.8-Beta single vm tests.
Tested locally:
```
openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-minimal.iso ARCH=x86_64 DISTRI=rocky FLAVOR=minimal-iso VERSION=8.8 CURRREL=8 DNF_CONTENTDIR=stg DNF_RELEASEVER=8.8-Beta BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.8-beta-minimal-iso
openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=package-set VERSION=8.8 CURREL=8 DNF_CONTENTDIR=stg DNF_RELEASEVER=8.8-Beta BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.8-beta-package-set
```
Result: All Pass
```
openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=universal VERSION=8.8 CURRREL=8 DNF_CONTENTDIR=stg DNF_RELEASEVER=8.8-Beta BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.8-beta-universal
```
Result: All Pass except mirrorlist since there isn't one for a beta release
```
openqa-cli api -X POST isos ISO=Rocky-8.8-x86_64-dvd1.iso ARCH=x86_64 DISTRI=rocky FLAVOR=dvd-iso VERSION=8.8 CURRREL=8 DNF_CONTENTDIR=stg DNF_RELEASEVER=8.8-Beta BUILD=-"$(date +%Y%m%d.%H%M%S).0"-8.8-beta-dvd-iso
```
Result: All Pass except base_update_cli & server_cockpit_updates which fail but not for needles. Both are being investigated elsewhere.

Will be tested on prod system shortly.

### CODE REVIEW

**Comment by AlanMarshall** [comment]
In prod system:
Following move of new needles to appropriate directories,  anaconda_help tested:
```
[BuildAlanMarshall/os-autoinst-distri-rocky#177](https://openqa.rockylinux.org/tests/overview?build=AlanMarshall/os-autoinst-distri-rocky#177&distri=rocky&version=8.8) of rocky-8.8-dvd-iso.x86_64 [anaconda_help@AlanMarshall/os-autoinst-distri-rocky#8.8_needles_1@64bit](https://openqa.rockylinux.org/tests/27302)
```
Result: Pass

@tcooper  When I try to run the server_cockpit_updates tests they fail with:
```
[error] HDD_1 handling Cannot find HDD_1 asset hdd/disk_64bit_cockpit.qcow2!
```
anaconda_help does not use HDD_1 (because no dependency?)
So the question seems to be how to clone tests that have dependencies.

**Comment by AlanMarshall** [comment]
If a clone job has dependencies then an extra step is necessary.  The helper script:
```
openqa-clone-custom-git-refspec --verbose --dry-run https://github.com/rocky-linux/os-autoinst-distri-rocky/pull/177 https://openqa.rockylinux.org/tests/27349
```
produces a run command:
```
/usr/bin/openqa-clone-job --skip-chained-deps --parental-inheritance --within-instance https://openqa.rockylinux.org 27349 _GROUP=0 TEST+=@AlanMarshall/os-autoinst-distri-rocky#8.8_needles_1 BUILD=AlanMarshall/os-autoinst-distri-rocky#177 CASEDIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#8.8_needles_1 PRODUCTDIR=os-autoinst-distri-rocky NEEDLES_DIR=rocky/needles
```
in ```NEEDLES_DIR=rocky/needles``` replace ```rocky``` with the contents of ```CASEDIR=``` and delete the parameter
``` --skip-chained-deps``` to give:
```
/usr/bin/openqa-clone-job --parental-inheritance --within-instance https://openqa.rockylinux.org 27349 _GROUP=0 TEST+=@AlanMarshall/os-autoinst-distri-rocky#8.8_needles_1 BUILD=AlanMarshall/os-autoinst-distri-rocky#177 CASEDIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#8.8_needles_1 PRODUCTDIR=os-autoinst-distri-rocky NEEDLES_DIR=https://github.com/AlanMarshall/os-autoinst-distri-rocky.git#8.8_needles_1/needles
```
which then produces:
```
Cloning parents of rocky-8.8-dvd-iso-x86_64-Build-20230508.135731.0-8.8-Beta-dvd-iso-server_cockpit_basic@64bit
Cloning parents of rocky-8.8-dvd-iso-x86_64-Build-20230508.135731.0-8.8-Beta-dvd-iso-server_cockpit_default@64bit
Cloning children of rocky-8.8-dvd-iso-x86_64-Build-20230508.135731.0-8.8-Beta-dvd-iso-install_default_upload@64bit
Cloning children of rocky-8.8-dvd-iso-x86_64-Build-20230508.135731.0-8.8-Beta-dvd-iso-server_cockpit_default@64bit
Created job #27365: rocky-8.8-dvd-iso-x86_64-Build-20230508.135731.0-8.8-Beta-dvd-iso-install_default_upload@64bit -> https://openqa.rockylinux.org/t27365
Created job #27367: rocky-8.8-dvd-iso-x86_64-Build-20230508.135731.0-8.8-Beta-dvd-iso-server_cockpit_basic@64bit -> https://openqa.rockylinux.org/t27367
Created job #27366: rocky-8.8-dvd-iso-x86_64-Build-20230508.135731.0-8.8-Beta-dvd-iso-server_cockpit_default@64bit -> https://openqa.rockylinux.org/t27366
```
on the cli and starts the jobs on the prod system.
Result: All Pass

base_update_cli & server_cockpit_updates still fail but are being investigated elsewhere therefore they are not relevant to this pr.

**Review by akatch — APPROVED** [review]
Changes work as advertised, cheers @AlanMarshall 🖖🏼

**Review by StackKorora — APPROVED** [review]
Looks good to me! Thanks!

**Pull request merged**
